AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  SAM Template for Suzume AWS Lambda function

Globals:
  Function:
    Timeout: 10

Resources:
  Suzume:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: main.main
      PackageType: Zip
      Runtime: python3.9
      Architectures: [ arm64 ]
