name: Master Branch

on:
  workflow_dispatch:
  push:
    branches:
      - master

concurrency:
  group: master-deploy
  cancel-in-progress: true

permissions:
  id-token: write
  contents: write

jobs:
  master-deploy:
    runs-on: ubuntu-latest
    env:
      SAM_CLI_TELEMETRY: 0
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
          token: ${{ secrets.GH_TOKEN }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::663412056516:role/GitHubActionsDeployLambda
          role-session-name: github-actions-suzume-deploy
          aws-region: eu-west-1

      - name: Build
        run: |
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
          make build-sam

      - name: Package
        id: package
        run: |
          OUTPUT="$(sam package --s3-bucket suzume-lambda --region eu-west-1 --force-upload)"
          S3_URI="$(echo "$OUTPUT" | grep -Eo "s3:\/\/(.+)")"
          S3_BUCKET="$(echo "$S3_URI" | cut -d "/" -f 3)"
          S3_KEY="$(echo "$S3_URI" | cut -d "/" -f 4)"
          echo "::set-output name=s3_bucket::$S3_BUCKET"
          echo "::set-output name=s3_key::$S3_KEY"
          echo "::set-output name=s3_uri::$S3_URI"

      - name: Deploy
        run: >
          aws lambda update-function-code
          --function arn:aws:lambda:eu-west-1:663412056516:function:suzume
          --s3-bucket ${{ steps.package.outputs.s3_bucket }}
          --s3-key ${{ steps.package.outputs.s3_key }}

      - name: Cleanup
        run: aws s3 delete ${{ steps.package.outputs.s3_uri }}
